CREATE TABLE IF NOT EXISTS hydrated_standard_schema (
   id uuid PRIMARY KEY,
    bikeid VARCHAR ( 255 ),
    birth_year VARCHAR ( 255 ),
    end_lat VARCHAR ( 255 ),
    end_lng VARCHAR ( 255 ),
    end_station_id VARCHAR ( 255 ),
    end_station_name VARCHAR ( 255 ),
    ended_at VARCHAR ( 255 ),
    gender VARCHAR ( 255 ),
    member_casual VARCHAR ( 255 ),
    ride_id VARCHAR ( 255 ),
    rideable_type VARCHAR ( 255 ),
    start_lat VARCHAR ( 255 ),
    start_lng VARCHAR ( 255 ),
    start_station_id VARCHAR ( 255 ),
    start_station_name VARCHAR ( 255 ),
    started_at VARCHAR ( 255 ),
    trip_duration VARCHAR ( 255 ),
);